=== qc-lab/QHyper/demo/wfcommons-schema.json
{"$schema": "http://json-schema.org/schema#", "type": "object", "title": "WfFormat", "properties": {"name": {"description": "Workflow instance name", "type": "string", "minLength": 1}, "description": {"description": "General description of the instance", "type": "string", "minLength": 1}, "createdAt": {"description": "Instance creation timestamp", "type": "string", "minLength": 1, "format": "date-time"}, "schemaVersion": {"description": "Version of the schema used", "type": "string", "enum": ["1.0", "1.1", "1.2", "1.3", "1.4"]}, "wms": {"type": "object", "properties": {"name": {"description": "WMS name", "type": "string", "minLength": 1}, "version": {"description": "WMS version", "type": "string", "minLength": 1}, "url": {"description": "WMS url", "type": "string", "minLength": 1, "format": "uri"}}, "required": ["name", "version"]}, "author": {"type": "object", "properties": {"name": {"description": "Author name", "type": "string", "minLength": 1}, "email": {"description": "Author email", "type": "string", "minLength": 1, "format": "email"}, "institution": {"description": "Author institution", "type": "string", "minLength": 1}, "country": {"description": "Author country", "type": "string", "minLength": 1}}, "required": ["name", "email"]}, "workflow": {"type": "object", "properties": {"makespanInSeconds": {"description": "Workflow makespan in seconds", "type": "number"}, "executedAt": {"description": "Workflow start execution timestamp", "type": "string", "minLength": 1}, "machines": {"description": "Sets of machines used for workflow tasks", "type": "array", "minItems": 1, "items": {"description": "Description of the machine (node) that ran the task", "type": "object", "properties": {"system": {"description": "Machine system", "type": "string", "enum": ["linux", "macos", "windows"]}, "architecture": {"description": "Machine architecture", "type": "string", "minLength": 1}, "nodeName": {"description": "Machine node name", "type": "string", "format": "hostname", "minLength": 1}, "release": {"description": "Machine release", "type": "string", "minLength": 1}, "memoryInBytes": {"description": "Total machine's RAM memory in bytes", "type": "integer", "minimum": 1}, "cpu": {"description": "Machine's CPU information", "type": "object", "properties": {"count": {"description": "Number of CPU cores", "type": "integer", "minimum": 1}, "speed": {"description": "CPU speed in MHz", "type": "integer", "minimum": 1}, "vendor": {"description": "CPU vendor", "type": "string", "minLength": 1}}}}, "required": ["nodeName"]}}, "tasks": {"description": "Sets of workflow tasks", "type": "array", "minItems": 1, "items": {"type": "object", "properties": {"name": {"description": "Task name", "type": "string", "minLength": 1}, "id": {"description": "Task ID", "type": "string", "minLength": 1}, "category": {"description": "Task category", "type": "string", "minLength": 1}, "type": {"description": "Task type (whether it is a compute or an auxiliary task)", "type": "string", "enum": ["compute", "transfer", "auxiliary"]}, "command": {"description": "Task command description", "type": "object", "properties": {"program": {"description": "Program name", "type": "string", "minLength": 1}, "arguments": {"description": "Sets of task arguments", "type": "array", "items": {"description": "A task argument", "type": "string", "minLength": 1}}}}, "parents": {"description": "Sets of parent tasks", "type": "array", "items": {"type": "string", "description": "Id of the parent task", "minLength": 1, "pattern": "^[0-9a-zA-Z-_.]*$"}}, "files": {"description": "Sets of input/output data", "type": "array", "items": {"type": "object", "properties": {"name": {"description": "A human-readable name for the file", "type": "string", "minLength": 1}, "sizeInBytes": {"description": "File size in bytes", "type": "integer", "minimum": 0}, "link": {"description": "Whether it is an input or output data", "type": "string", "enum": ["input", "output"]}}, "required": ["name", "sizeInBytes", "link"]}}, "runtimeInSeconds": {"description": "Task runtime in seconds", "type": "number"}, "cores": {"description": "Number of cores required by the task", "type": "number", "minimum": 1}, "avgCPU": {"description": "Average CPU utilization in %", "type": "number"}, "readBytes": {"description": "Total bytes read", "type": "number"}, "writtenBytes": {"description": "Total bytes written", "type": "number"}, "memoryInBytes": {"description": "Memory (resident set) size of the process in bytes", "type": "number"}, "energy": {"description": "Total energy consumption in kWh", "type": "number"}, "avgPower": {"description": "Average power consumption in W", "type": "number"}, "priority": {"description": "Task priority", "type": "number"}, "machine": {"description": "Machine name used", "type": "string", "minLength": 1}}, "required": ["name", "type"]}}}, "required": ["makespanInSeconds", "executedAt", "tasks"]}}, "required": ["name", "schemaVersion", "workflow"]}

=== qc-lab/QHyper/demo/workflows_data/workflows/1000genome_22_tasks.json
{
    "name": "workflow-test",
    "description": "Trace generated with WorkflowHub - https://workflowhub.org",
    "createdAt": "2020-12-19T23:38:32.986156",
    "schemaVersion": "1.4",
    "author": {
        "name": "rafsilva",
        "email": "support@workflowhub.org"
    },
    "wms": {
        "name": "Pegasus",
        "version": "5.0",
        "url": "https://pegasus.isi.edu"
    },
    "workflow": {
        "executedAt": "12-19-20T21:31:53Z",
        "machines": [
            {
                "nodeName": "worker-4",
                "system": "linux",
                "architecture": "x86_64",
                "release": "4.15.0-121-generic",
                "cpu": {
                    "count": 48,
                    "speed": 1274,
                    "vendor": "GenuineIntel"
                },
                "memoryInBytes": 131795960000
            }
        ],
        "tasks": [
            {
                "name": "bowtie2-build_ID0000001",
                "type": "compute",
                "parents": [],
                "children": [
                    "bowtie2_ID0000003",
                    "bowtie2_ID0000013",
                    "bowtie2_ID0000005",
                    "bowtie2_ID0000015",
                    "bowtie2_ID0000021",
                    "bowtie2_ID0000011",
                    "bowtie2_ID0000007",
                    "bowtie2_ID0000017",
                    "bowtie2_ID0000009",
                    "bowtie2_ID0000019"
                ],
                "files": [
                    {
                        "link": "output",
                        "name": "reference.rev.1.bt2",
                        "sizeInBytes": 4226858
                    },
                    {
                        "link": "output",
                        "name": "reference.2.bt2",
                        "sizeInBytes": 24280
                    },
                    {
                        "link": "output",
                        "name": "reference.4.bt2",
                        "sizeInBytes": 24273
                    },
                    {
                        "link": "output",
                        "name": "reference.3.bt2",
                        "sizeInBytes": 17
                    },
                    {
                        "link": "output",
                        "name": "reference.1.bt2",
                        "sizeInBytes": 4226858
                    },
                    {
                        "link": "output",
                        "name": "reference.rev.2.bt2",
                        "sizeInBytes": 24280
                    },
                    {
                        "link": "input",
                        "name": "reference.fna",
                        "sizeInBytes": 98721
                    }
                ],
                "avgCPU": 6.1398,
                "memory": 94720,
                "priority": 20,
                "machine": "worker-4",
                "id": "ID0000001",
                "category": "bowtie2-build",
                "command": {
                    "program": "bowtie2-build",
                    "arguments": [
                        "reference.fna",
                        "reference"
                    ]
                },
                "runtimeInSeconds": 6.352,
                "memoryInBytes": 94720000
            },
            {
                "name": "fasterq-dump_ID0000002",
                "type": "compute",
                "parents": [],
                "children": [
                    "bowtie2_ID0000003"
                ],
                "files": [
                    {
                        "link": "output",
                        "name": "SRR3152141_2.fastq",
                        "sizeInBytes": 734761744
                    },
                    {
                        "link": "output",
                        "name": "SRR3152141_1.fastq",
                        "sizeInBytes": 734761744
                    }
                ],
                "avgCPU": 3.5286,
                "memory": 324392,
                "priority": 20,
                "machine": "worker-4",
                "id": "ID0000002",
                "category": "fasterq-dump",
                "command": {
                    "program": "fasterq-dump",
                    "arguments": [
                        "--split-files",
                        "SRR3152141"
                    ]
                },
                "runtimeInSeconds": 896.867,
                "memoryInBytes": 324392000
            },
            {
                "name": "bowtie2_ID0000003",
                "type": "compute",
                "parents": [
                    "bowtie2-build_ID0000001",
                    "fasterq-dump_ID0000002"
                ],
                "children": [
                    "merge_ID0000022"
                ],
                "files": [
                    {
                        "link": "input",
                        "name": "reference.rev.1.bt2",
                        "sizeInBytes": 4226858
                    },
                    {
                        "link": "input",
                        "name": "reference.2.bt2",
                        "sizeInBytes": 24280
                    },
                    {
                        "link": "input",
                        "name": "reference.4.bt2",
                        "sizeInBytes": 24273
                    },
                    {
                        "link": "input",
                        "name": "reference.3.bt2",
                        "sizeInBytes": 17
                    },
                    {
                        "link": "output",
                        "name": "SRR3152141.bam",
                        "sizeInBytes": 316
                    },
                    {
                        "link": "input",
                        "name": "SRR3152141_1.fastq",
                        "sizeInBytes": 734761744
                    },
                    {
                        "link": "input",
                        "name": "reference.1.bt2",
                        "sizeInBytes": 4226858
                    },
                    {
                        "link": "output",
                        "name": "SRR3152141.bam.bai",
                        "sizeInBytes": 24
                    },
                    {
                        "link": "input",
                        "name": "reference.rev.2.bt2",
                        "sizeInBytes": 24280
                    },
                    {
                        "link": "input",
                        "name": "SRR3152141_2.fastq",
                        "sizeInBytes": 734761744
                    }
                ],
                "avgCPU": 103.8255,
                "memory": 27096,
                "priority": 30,
                "machine": "worker-4",
                "id": "ID0000003",
                "category": "bowtie2",
                "command": {
                    "program": "bowtie2",
                    "arguments": [
                        "SRR3152141"
                    ]
                },
                "runtimeInSeconds": 54.137,
                "memoryInBytes": 27096000
            },
            {
                "name": "fasterq-dump_ID0000004",
                "type": "compute",
                "parents": [],
                "children": [
                    "bowtie2_ID0000005"
                ],
                "files": [
                    {
                        "link": "output",
                        "name": "SRR3152151_1.fastq",
                        "sizeInBytes": 345787144
                    },
                    {
                        "link": "output",
                        "name": "SRR3152151_2.fastq",
                        "sizeInBytes": 345787144
                    }
                ],
                "avgCPU": 3.4026,
                "memory": 187340,
                "priority": 20,
                "machine": "worker-4",
                "id": "ID0000004",
                "category": "fasterq-dump",
                "command": {
                    "program": "fasterq-dump",
                    "arguments": [
                        "--split-files",
                        "SRR3152151"
                    ]
                },
                "runtimeInSeconds": 452.479,
                "memoryInBytes": 187340000
            },
            {
                "name": "bowtie2_ID0000005",
                "type": "compute",
                "parents": [
                    "bowtie2-build_ID0000001",
                    "fasterq-dump_ID0000004"
                ],
                "children": [
                    "merge_ID0000022"
                ],
                "files": [
                    {
                        "link": "input",
                        "name": "reference.rev.1.bt2",
                        "sizeInBytes": 4226858
                    },
                    {
                        "link": "input",
                        "name": "reference.2.bt2",
                        "sizeInBytes": 24280
                    },
                    {
                        "link": "output",
                        "name": "SRR3152151.bam.bai",
                        "sizeInBytes": 24
                    },
                    {
                        "link": "input",
                        "name": "reference.4.bt2",
                        "sizeInBytes": 24273
                    },
                    {
                        "link": "input",
                        "name": "reference.3.bt2",
                        "sizeInBytes": 17
